apiVersion: v1
kind: ReplicationController
metadata:
  name: webrc
  labels:
    name: webrc
    app: demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: webrc
    spec:
      containers:
        - name: webrc
          image: xiaopeng163/docker-flask-demo:1.0
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
